//go:build objectbox

package objectboxstorage

import (
	"encoding/json"
	"fmt"

	obx "github.com/objectbox/objectbox-go/objectbox"

	"github.com/ElizioMartins/objectbox-graph/graph"
)

// ObjectBoxStorage implements graph.Storage using ObjectBox as the backend.
//
// This is the bridge between objectbox-graph's algorithm layer and ObjectBox's
// high-performance on-device storage — the same pattern used by pgvector
// (extending PostgreSQL) and MongoDB Atlas Vector Search.
type ObjectBoxStorage struct {
	store   *obx.ObjectBox
	nodeBox *NodeEntityBox // generated by objectbox-gogen
	edgeBox *EdgeEntityBox // generated by objectbox-gogen
}

// New creates a new ObjectBoxStorage backed by an existing ObjectBox store.
//
// Example:
//
//	obxStore, _ := objectbox.NewBuilder().
//	    Model(ObjectBoxModel()).
//	    Directory("my-graph-db").
//	    Build()
//
//	storage, _ := objectboxstorage.New(obxStore)
//	g := graph.New(storage)
func New(store *obx.ObjectBox) (*ObjectBoxStorage, error) {
	return &ObjectBoxStorage{
		store:   store,
		nodeBox: BoxForNodeEntity(store),
		edgeBox: BoxForEdgeEntity(store),
	}, nil
}

func (s *ObjectBoxStorage) PutNode(node *graph.Node) (uint64, error) {
	props, err := json.Marshal(node.Properties)
	if err != nil {
		return 0, fmt.Errorf("PutNode marshal properties: %w", err)
	}
	entity := &NodeEntity{
		Id:         node.Id,
		Label:      node.Label,
		Properties: string(props),
	}
	id, err := s.nodeBox.Put(entity)
	if err != nil {
		return 0, fmt.Errorf("PutNode: %w", err)
	}
	return id, nil
}

func (s *ObjectBoxStorage) GetNode(id uint64) (*graph.Node, error) {
	entity, err := s.nodeBox.Get(id)
	if err != nil {
		return nil, fmt.Errorf("GetNode: %w", err)
	}
	if entity == nil {
		return nil, fmt.Errorf("node %d not found", id)
	}
	return nodeEntityToGraph(entity), nil
}

func (s *ObjectBoxStorage) AllNodes() ([]*graph.Node, error) {
	entities, err := s.nodeBox.GetAll()
	if err != nil {
		return nil, err
	}
	result := make([]*graph.Node, len(entities))
	for i, e := range entities {
		result[i] = nodeEntityToGraph(e)
	}
	return result, nil
}

func (s *ObjectBoxStorage) RemoveNode(id uint64) error {
	return s.nodeBox.Remove(&NodeEntity{Id: id})
}

func (s *ObjectBoxStorage) PutEdge(edge *graph.Edge) (uint64, error) {
	entity := &EdgeEntity{
		Id:     edge.Id,
		FromId: edge.FromId,
		ToId:   edge.ToId,
		Label:  edge.Label,
		Weight: edge.Weight,
	}
	id, err := s.edgeBox.Put(entity)
	if err != nil {
		return 0, fmt.Errorf("PutEdge: %w", err)
	}
	return id, nil
}

func (s *ObjectBoxStorage) GetEdge(id uint64) (*graph.Edge, error) {
	entity, err := s.edgeBox.Get(id)
	if err != nil {
		return nil, err
	}
	if entity == nil {
		return nil, fmt.Errorf("edge %d not found", id)
	}
	return edgeEntityToGraph(entity), nil
}

// EdgesFrom returns all edges with FromId == nodeId.
// This is the core traversal query — ObjectBox's integer index makes
// this O(log n) instead of the O(n) scan that a naive approach would require.
func (s *ObjectBoxStorage) EdgesFrom(nodeId uint64) ([]*graph.Edge, error) {
	q, err := s.edgeBox.Query(EdgeEntity_.FromId.Equals(nodeId))
	if err != nil {
		return nil, err
	}
	defer q.Close()
	entities, err := q.Find()
	if err != nil {
		return nil, err
	}
	result := make([]*graph.Edge, len(entities))
	for i, e := range entities {
		result[i] = edgeEntityToGraph(e)
	}
	return result, nil
}

// EdgesTo returns all edges with ToId == nodeId (for reverse traversal).
func (s *ObjectBoxStorage) EdgesTo(nodeId uint64) ([]*graph.Edge, error) {
	q, err := s.edgeBox.Query(EdgeEntity_.ToId.Equals(nodeId))
	if err != nil {
		return nil, err
	}
	defer q.Close()
	entities, err := q.Find()
	if err != nil {
		return nil, err
	}
	result := make([]*graph.Edge, len(entities))
	for i, e := range entities {
		result[i] = edgeEntityToGraph(e)
	}
	return result, nil
}

func (s *ObjectBoxStorage) AllEdges() ([]*graph.Edge, error) {
	entities, err := s.edgeBox.GetAll()
	if err != nil {
		return nil, err
	}
	result := make([]*graph.Edge, len(entities))
	for i, e := range entities {
		result[i] = edgeEntityToGraph(e)
	}
	return result, nil
}

func (s *ObjectBoxStorage) RemoveEdge(id uint64) error {
	return s.edgeBox.Remove(&EdgeEntity{Id: id})
}

func (s *ObjectBoxStorage) Close() error {
	s.store.Close()
	return nil
}

// --- internal converters ---

func nodeEntityToGraph(e *NodeEntity) *graph.Node {
	var props map[string]string
	_ = json.Unmarshal([]byte(e.Properties), &props)
	return &graph.Node{Id: e.Id, Label: e.Label, Properties: props}
}

func edgeEntityToGraph(e *EdgeEntity) *graph.Edge {
	return &graph.Edge{
		Id: e.Id, FromId: e.FromId, ToId: e.ToId,
		Label: e.Label, Weight: e.Weight,
	}
}
